### ISSUE TITLE
This procedure how to deal with grayscale images?

### ISSUE THREAD

**Issue by liufenglin** [AlpacaDB/selectivesearch#27]
hello！
Thank you very much for sharing the code！
But I have a problem, that is, when I input the grayscale image , the program will give an error：

Traceback (most recent call last):
  File "example.py", line 91, in <module>
    main()
  File "example.py", line 35, in main
    img, scale=5000, sigma=0.9, min_size=10)
  File "D:\selectivesearch-develop\selectivesearch\selectivesearch.py", line 264, in selective_search
    assert im_orig.shape[2] == 3, "3ch image is expected"
IndexError: tuple index out of range

Looking forward to your reply！！
best

**Comment by neozgx** [comment]
Because you grayscale two times，before the selectivesearch

**Comment by neozgx** [comment]
![qq](https://user-images.githubusercontent.com/29486192/35666161-e0c170ca-0763-11e8-8240-4fc2885927f3.jpg)

**Comment by liufenglin** [comment]
Thank you so much！！！

**Comment by yingwei13mei** [comment]
I wrote as follows, but cannot come out 
    img2="IMG_0002.jpg"   #this is a grayscale img
    img=cv2.imread(img2)
    # perform selective search
    img_lbl, regions = selective_search(
        img, scale=200, sigma=0.9, min_size=10)
